In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/corpus01/01_corpus_turismo_500.txt


In [100]:
ruta = '/kaggle/input/corpus01/01_corpus_turismo_500.txt'
with open(ruta, 'r',encoding = 'utf-8' ) as f:
    text = f.read()

In [101]:
#la variable text contiene todo el corpus
text

'Otavalo es conocido por su mercado indígena y su artesanía Perfecto para rafting.\nLa Laguna Quilotoa destaca por su color turquesa\nVilcabamba atrae visitantes interesados en longevidad y naturaleza Una experiencia inolvidable.\nQuito tiene un centro histórico Patrimonio de la Humanidad Perfecto para surf.\nEcuador es un país megadiverso, ideal para el turismo ecológico\nLos turistas disfrutan las fiestas y gastronomía típica local Perfecto para avistamiento de aves.\nOtavalo es conocido por su mercado indígena y su artesanía Una experiencia inolvidable.\nEl volcán Cotopaxi es un destino de senderismo popular\nEl Parque Nacional Cajas invita a caminatas entre lagunas Ideal para el próximo feriado.\nMindo es famoso por el avistamiento de aves Ideal para el próximo feriado.\nCuenca deslumbra con su arquitectura colonial y gastronomía Una experiencia inolvidable.\nLas Islas Galápagos atraen visitantes por su biodiversidad única Ideal para el próximo feriado.\nGuayaquil sorprende con su 

In [102]:
#set(text.split(' '))
set(text.replace('\n', ' ').replace('.', ' ').replace(',', ' ').split())

{'2000',
 'Agua',
 'Amazonía',
 'Baños',
 'Cajas',
 'Cotopaxi',
 'Cuenca',
 'Durante',
 'Ecuador',
 'El',
 'Galápagos',
 'Guayaquil',
 'Humanidad',
 'Ideal',
 'Islas',
 'La',
 'Laguna',
 'Las',
 'Los',
 'Malecón',
 'Mindo',
 'Montañita',
 'Nacional',
 'Otavalo',
 'Parque',
 'Patrimonio',
 'Perfecto',
 'Quilotoa',
 'Quito',
 'Ruta',
 'Santa',
 'Spondylus',
 'Un',
 'Una',
 'Vilcabamba',
 'a',
 'arquitectura',
 'artesanía',
 'atrae',
 'atraen',
 'auténtico',
 'aventura',
 'aves',
 'avistamiento',
 'biodiversidad',
 'caminatas',
 'canopy',
 'centro',
 'colonial',
 'color',
 'como',
 'con',
 'conecta',
 'conocido',
 'de',
 'del',
 'deportes',
 'deslumbra',
 'destaca',
 'destino',
 'disfrutan',
 'durante',
 'ecológico',
 'ecuatoriana',
 'el',
 'en',
 'entre',
 'es',
 'espectacular',
 'experiencia',
 'famosas',
 'famoso',
 'feriado',
 'feriados',
 'fiestas',
 'gastronomía',
 'histórico',
 'ideal',
 'increíble',
 'indígena',
 'inolvidable',
 'interesados',
 'invita',
 'la',
 'lagunas',
 'las',

In [105]:
# boolean -> ',' in text
vocab = list(set(text.lower().replace('\n', ' ').replace('.', ' ').replace(',', ' ').split()))
vocab

['ecuatoriana',
 'popular',
 'inolvidable',
 'para',
 'próximo',
 'país',
 'única',
 'feriados',
 'atraen',
 'la',
 'un',
 'experiencia',
 'nocturna',
 'atrae',
 'otavalo',
 'quito',
 'ideal',
 'una',
 'conecta',
 'sorprende',
 'color',
 'famoso',
 'fiestas',
 'cotopaxi',
 'cajas',
 'guayaquil',
 'spondylus',
 'aventura',
 'entre',
 'como',
 'ecológico',
 'visitan',
 'mindo',
 'arquitectura',
 'caminatas',
 'por',
 'conocido',
 'biodiversidad',
 'galápagos',
 'muchos',
 'longevidad',
 'turismo',
 'centro',
 'parque',
 'mercado',
 'llena',
 'aves',
 'avistamiento',
 'durante',
 'surfistas',
 'patrimonio',
 'quilotoa',
 'megadiverso',
 'rafting',
 'invita',
 'del',
 'es',
 'indígena',
 'con',
 'ecuador',
 'su',
 'ruta',
 'tiene',
 'increíble',
 'histórico',
 'destaca',
 'artesanía',
 'de',
 'se',
 'y',
 'sorprendente',
 'a',
 'vida',
 'en',
 'volcán',
 'auténtico',
 'deportes',
 'agua',
 'senderismo',
 'destino',
 'turquesa',
 'gastronomía',
 'naturaleza',
 'famosas',
 'el',
 'colonial',

In [106]:
len(vocab)

118

In [107]:
corpus = text.split('\n')
corpus
    

['Otavalo es conocido por su mercado indígena y su artesanía Perfecto para rafting.',
 'La Laguna Quilotoa destaca por su color turquesa',
 'Vilcabamba atrae visitantes interesados en longevidad y naturaleza Una experiencia inolvidable.',
 'Quito tiene un centro histórico Patrimonio de la Humanidad Perfecto para surf.',
 'Ecuador es un país megadiverso, ideal para el turismo ecológico',
 'Los turistas disfrutan las fiestas y gastronomía típica local Perfecto para avistamiento de aves.',
 'Otavalo es conocido por su mercado indígena y su artesanía Una experiencia inolvidable.',
 'El volcán Cotopaxi es un destino de senderismo popular',
 'El Parque Nacional Cajas invita a caminatas entre lagunas Ideal para el próximo feriado.',
 'Mindo es famoso por el avistamiento de aves Ideal para el próximo feriado.',
 'Cuenca deslumbra con su arquitectura colonial y gastronomía Una experiencia inolvidable.',
 'Las Islas Galápagos atraen visitantes por su biodiversidad única Ideal para el próximo fer

In [108]:
doc = corpus[0]
doc

'Otavalo es conocido por su mercado indígena y su artesanía Perfecto para rafting.'

In [109]:
doc.split().count('es')

1

In [110]:
import numpy as np
def get_tf(doc):
    vec =[]
    for word in vocab:
        cont = doc.lower().replace('.', '').replace(',', '').split().count(word)
        vec.append(cont)
    return np.array(vec)

In [111]:
x = get_tf(corpus[0])
x

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
corpus_vec = []
for doc in corpus:
    doc_vec = get_tf(doc)
    corpus_vec.append(doc_vec)

In [113]:
print(corpus_vec)

[array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [116]:
df_t = np.sum(corpus_vec, axis=0)
df_t

array([ 27,  27,  96, 346, 118,  36,  33,  27,  33, 126, 175,  96,  33,
        27,  33,  20, 154,  96,  47,  33,  32,  40,  32,  27,  37,  33,
        47,  32,  37,  79,  36,  27,  23,  34,  37, 121,  33,  33,  33,
        27,  27,  36,  20,  37,  33,  27,  44,  44,  54,  27,  20,  32,
        36,  54,  37,  47, 119,  33,  67,  36, 198,  47,  20,  11,  20,
        32,  33, 182,  27, 159,  15,  37,  33,  27,  27,  13,  32,  32,
        44,  27,  32,  66,  27,  47, 268,  34, 100,  92,  32,  32,  16,
        32,  74,  65,  92,  17,  20,  23,  37,  60, 145,  32,  20,  27,
        47,  32,  37,  33,  34,  34,  33,  32,  32,  33,  59,  32,  27,
        27])

In [123]:
y = np.divide(118, df_t)

In [126]:
idf = np.log(y)
idf

array([ 1.47484776,  1.47484776,  0.20633643, -1.07575415,  0.        ,
        1.18716569,  1.27417706,  1.47484776,  1.27417706, -0.06559728,
       -0.39410135,  0.20633643,  1.27417706,  1.47484776,  1.27417706,
        1.77495235, -0.26626798,  0.20633643,  0.92053702,  1.27417706,
        1.30494872,  1.08180517,  1.30494872,  1.47484776,  1.15976671,
        1.27417706,  0.92053702,  1.30494872,  1.15976671,  0.40123677,
        1.18716569,  1.47484776,  1.63519041,  1.2443241 ,  1.15976671,
       -0.02510592,  1.27417706,  1.27417706,  1.27417706,  1.47484776,
        1.47484776,  1.18716569,  1.77495235,  1.15976671,  1.27417706,
        1.47484776,  0.98649499,  0.98649499,  0.78170058,  1.47484776,
        1.77495235,  1.30494872,  1.18716569,  0.78170058,  1.15976671,
        0.92053702, -0.00843887,  1.27417706,  0.56599201,  1.18716569,
       -0.51758241,  0.92053702,  1.77495235,  2.37278935,  1.77495235,
        1.30494872,  1.27417706, -0.43332206,  1.47484776, -0.29

In [128]:
corpus_vec * idf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.20633643, ..., 0.        , 1.47484776,
        1.47484776],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.30494872, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
def get_idf(doc):
    log(N/(df_t + 1))
    